export default NavigationScreenNames = {
    Login: 'login',
    SignIn: 'signin',
    SignUp: 'signUp',
    Forgot: 'forgot',
    Home: 'home',
    Dashboard: 'dashboard',
    Wallet: 'wallet',
    Message: 'message',
    History: 'history',
    Profile: 'profile',
    DrawMain: 'drawmain',
    DrawerOpen: 'draweropen',
    DrawerClose: 'drawerclose',
    CreateCard: 'createcard',
    TransferMoney: 'transfer_money',
    TransferByWallet: 'transfer_by_wallet',
    EnterMoney: 'enter_money',
    Finish: 'finish_after_transfer_money',
    Invoice: 'pay_invoice',
};
